docs:
  image: centos:7
  volumes:
    - ./files:/data/docs

webapp:
  build: oddjob
  volumes:
    - ./oddjob:/opt/oddjob
  volumes_from:
    - docs
  links:
    - postgres
  working_dir: /opt/oddjob
  command: bash start-app.sh
  environment:
    - DB_USER=username
    - DB_PASS=password
    - DB_NAME=database

scraper:
  build: scraper
  links:
    - webapp
  volumes:
    - ./scraper:/opt/scraper
  volumes_from:
    - docs
  working_dir: /opt/scraper
  command: python scraper.py

nginx:
  build: nginx
  links:
    - webapp
  volumes_from:
    - docs
  volumes:
    - ./oddjob:/opt/oddjob
  ports:
   - "8000:80"

postgres:
  build: postgres
  environment:
    - DB_USER=username
    - DB_PASS=password
    - DB_NAME=database
